### PR TITLE
Base pool factory update

### PR DESCRIPTION
**Pull request by baileyspraggins**
This PR updates all LinearPoolFactories to utilize the updated BasePoolFactory. This change involves adding an extra argument to the `_create` function inherited from the BasePoolFactory to account for a newly added `bytes32 salt` parameter.

Additional changes include:
- Updating all build info and artifacts within the `fork-test` directory

Additional notes:
**DO NOT MERGE** until lint fix PR is complete

### CODE REVIEW

**Review by mkflow27 — APPROVED** [review]
This looks good. Once thing I am not certain is how we should handle versions. @Rab can probably chime in here.

**Comment by 0xpatrooney** [comment]
Mentioned the wrong person, oops. Meant @rabmarut

**Comment by baileyspraggins** [comment]
> This looks good. Once thing I am not certain is how we should handle versions. @rab can probably chime in here.

@rabmarut

**Review by rabmarut — CHANGES_REQUESTED** [review]
This PR seems to make a ton of style changes throughout the fork tests. That's a fine thing to do, but it doesn't really mesh with the BasePoolFactory update. Can we split this into two PRs?

**Review by rabmarut — CHANGES_REQUESTED** [review]
This PR adds artifacts for some pool types that never had them (Euler, Aave). While I agree that this was an oversight, let's save those additions for the other cleanup PR so that we can keep the change count to a minimum in this one. It's still okay to include changes to existing build-info and artifacts in this PR, but let's not introduce any net-new files. I hope that makes sense.

Also, I should have been more specific about how we want to implement this change - sorry for the oversight. Rather than auto-generating the salt for pools, like we do for rebalancers, we should instead allow the caller to specify a salt. This enables the caller to create arbitrary deployment addresses for pools, including vanity addresses if that's desirable.

We should continue to auto-generate the salt for the rebalancers as we do now. But for pools, we can simply pass salt into the external `create` call. See the [`WeightedPoolFactory`](https://github.com/balancer/balancer-v2-monorepo/blob/90d9d229d1dc02758ec4c9b065d60b563d32b7bd/pkg/pool-weighted/contracts/WeightedPoolFactory.sol#L53) for reference.

**Comment by baileyspraggins** [comment]
> This PR adds artifacts for some pool types that never had them (Euler, Aave). While I agree that this was an oversight, let's save those additions for the other cleanup PR so that we can keep the change count to a minimum in this one. It's still okay to include changes to existing build-info and artifacts in this PR, but let's not introduce any net-new files. I hope that makes sense.
> 
> Also, I should have been more specific about how we want to implement this change - sorry for the oversight. Rather than auto-generating the salt for pools, like we do for rebalancers, we should instead allow the caller to specify a salt. This enables the caller to create arbitrary deployment addresses for pools, including vanity addresses if that's desirable.
> 
> We should continue to auto-generate the salt for the rebalancers as we do now. But for pools, we can simply pass salt into the external `create` call. See the [`WeightedPoolFactory`](https://github.com/balancer/balancer-v2-monorepo/blob/90d9d229d1dc02758ec4c9b065d60b563d32b7bd/pkg/pool-weighted/contracts/WeightedPoolFactory.sol#L53) for reference.

Ok that makes sense. I'll make those changes tonight. In terms of adding the artifacts for Euler and Aave, is that something that can be added to the existing [fork-tests PR](https://github.com/orbcollective/linear-pools/pull/31) or should I create an additional PR specifically for the new artifacts?

**Review by rabmarut — APPROVED** [review]

**Pull request merged**
